# Generated by Django 3.2.3 on 2021-05-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='user_name',
        ),
    ]
