# Generated by Django 3.2.3 on 2021-05-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_alter_hire_adoption_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire',
            old_name='adoption_id',
            new_name='adopt_id',
        ),
    ]
