# Generated by Django 3.2.3 on 2021-05-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='page',
        ),
    ]
