# Generated by Django 3.2.3 on 2021-05-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='total_animals',
            field=models.IntegerField(),
        ),
    ]
