# Generated by Django 3.2.2 on 2021-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='photo',
            field=models.ImageField(upload_to='media/caret/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='preferred_animal',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Horse', 'Horse'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Bird', 'Bird'), ('Rat', 'Rat')], max_length=255),
        ),
    ]
