# Generated by Django 3.2.3 on 2021-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0002_auto_20210507_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='age',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
