# Generated by Django 3.2.3 on 2021-05-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0003_auto_20210514_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='price',
            field=models.IntegerField(),
        ),
    ]
