# Generated by Django 3.2.3 on 2021-05-15 03:57

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=2055)),
                ('number', models.CharField(default='', max_length=2055)),
                ('clinic', models.CharField(default='', max_length=2955)),
                ('photo', models.ImageField(upload_to='media/adopt/%Y/%m/')),
                ('description', ckeditor.fields.RichTextField(default='')),
                ('degree', models.CharField(default='', max_length=555)),
                ('fee', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
