# Generated by Django 3.2.1 on 2021-05-07 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/ytubers/%Y/%m/')),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('weight', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
