# Generated by Django 3.2.2 on 2021-05-07 08:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='animal',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Horse', 'Horse'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Bird', 'Bird'), ('Rat', 'Rat')], max_length=255),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
