# Generated by Django 3.2.2 on 2021-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_auto_20210507_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='age',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='photo',
            field=models.ImageField(upload_to='media/adopt/%Y/%m/'),
        ),
    ]
