# Generated by Django 3.2.2 on 2021-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_auto_20210507_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='height',
            field=models.CharField(max_length=255),
        ),
    ]
