# Generated by Django 3.2.3 on 2021-05-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirec',
            old_name='ct_id',
            new_name='care_id',
        ),
    ]
